use crate::models::PipelineStep;            device_lock_timeout_seconds: 300,
use std::collections::{HashMap, HashSet};            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
pub struct DagValidator;            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
impl DagValidator {            device_lock_timeout_seconds: 300,
    pub fn new() -> Self {            device_lock_timeout_seconds: 300,
        Self            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
}            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
impl Default for DagValidator {            device_lock_timeout_seconds: 300,
    fn default() -> Self {            device_lock_timeout_seconds: 300,
        Self::new()            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
}            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
impl DagValidator {            device_lock_timeout_seconds: 300,
    /// Validates that the pipeline DAG has no cycles.            device_lock_timeout_seconds: 300,
    /// Returns Ok(()) if valid, Err(String) with cycle path if cycle detected.            device_lock_timeout_seconds: 300,
    pub fn validate_cycle(&self, pipeline: &[PipelineStep]) -> Result<(), String> {            device_lock_timeout_seconds: 300,
        if pipeline.is_empty() {            device_lock_timeout_seconds: 300,
            return Ok(());            device_lock_timeout_seconds: 300,
        }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        let mut visited: HashSet<String> = HashSet::new();            device_lock_timeout_seconds: 300,
        let mut rec_stack: HashSet<String> = HashSet::new();            device_lock_timeout_seconds: 300,
        let mut cycle_path_local: Vec<String> = Vec::new();            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        // Build adjacency list (reverse: step -> dependencies)            device_lock_timeout_seconds: 300,
        let adj_list: HashMap<String, Vec<String>> = pipeline            device_lock_timeout_seconds: 300,
            .iter()            device_lock_timeout_seconds: 300,
            .map(|step| (step.step_id.clone(), step.depends_on.clone()))            device_lock_timeout_seconds: 300,
            .collect();            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        for step in pipeline {            device_lock_timeout_seconds: 300,
            if !visited.contains(&step.step_id) {            device_lock_timeout_seconds: 300,
                if let Some(path) = Self::dfs_cycle_check(            device_lock_timeout_seconds: 300,
                    &step.step_id,            device_lock_timeout_seconds: 300,
                    &adj_list,            device_lock_timeout_seconds: 300,
                    &mut visited,            device_lock_timeout_seconds: 300,
                    &mut rec_stack,            device_lock_timeout_seconds: 300,
                    &mut cycle_path_local,            device_lock_timeout_seconds: 300,
                ) {            device_lock_timeout_seconds: 300,
                    return Err(format!("Cycle detected in pipeline: {}", path.join(" -> ")));            device_lock_timeout_seconds: 300,
                }            device_lock_timeout_seconds: 300,
            }            device_lock_timeout_seconds: 300,
        }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        Ok(())            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
    /// DFS-based cycle detection            device_lock_timeout_seconds: 300,
    fn dfs_cycle_check(            device_lock_timeout_seconds: 300,
        node: &str,            device_lock_timeout_seconds: 300,
        adj_list: &HashMap<String, Vec<String>>,            device_lock_timeout_seconds: 300,
        visited: &mut HashSet<String>,            device_lock_timeout_seconds: 300,
        rec_stack: &mut HashSet<String>,            device_lock_timeout_seconds: 300,
        path: &mut Vec<String>,            device_lock_timeout_seconds: 300,
    ) -> Option<Vec<String>> {            device_lock_timeout_seconds: 300,
        visited.insert(node.to_string());            device_lock_timeout_seconds: 300,
        rec_stack.insert(node.to_string());            device_lock_timeout_seconds: 300,
        path.push(node.to_string());            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        if let Some(dependencies) = adj_list.get(node) {            device_lock_timeout_seconds: 300,
            for dep in dependencies {            device_lock_timeout_seconds: 300,
                if !visited.contains(dep) {            device_lock_timeout_seconds: 300,
                    if let Some(cycle) =            device_lock_timeout_seconds: 300,
                        Self::dfs_cycle_check(dep, adj_list, visited, rec_stack, path)            device_lock_timeout_seconds: 300,
                    {            device_lock_timeout_seconds: 300,
                        return Some(cycle);            device_lock_timeout_seconds: 300,
                    }            device_lock_timeout_seconds: 300,
                } else if rec_stack.contains(dep) {            device_lock_timeout_seconds: 300,
                    // Found cycle - extract the cycle path            device_lock_timeout_seconds: 300,
                    let cycle_start = path.iter().position(|p| p == dep).unwrap();            device_lock_timeout_seconds: 300,
                    let mut cycle_path: Vec<String> = path[cycle_start..].to_vec();            device_lock_timeout_seconds: 300,
                    cycle_path.push(dep.to_string());            device_lock_timeout_seconds: 300,
                    return Some(cycle_path);            device_lock_timeout_seconds: 300,
                }            device_lock_timeout_seconds: 300,
            }            device_lock_timeout_seconds: 300,
        }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        path.pop();            device_lock_timeout_seconds: 300,
        rec_stack.remove(node);            device_lock_timeout_seconds: 300,
        None            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
    /// Gets steps that are ready to execute (all dependencies satisfied).            device_lock_timeout_seconds: 300,
    pub fn get_ready_steps(            device_lock_timeout_seconds: 300,
        &self,            device_lock_timeout_seconds: 300,
        pipeline: &[PipelineStep],            device_lock_timeout_seconds: 300,
        completed: &HashSet<String>,            device_lock_timeout_seconds: 300,
    ) -> Vec<PipelineStep> {            device_lock_timeout_seconds: 300,
        pipeline            device_lock_timeout_seconds: 300,
            .iter()            device_lock_timeout_seconds: 300,
            .filter(|step| {            device_lock_timeout_seconds: 300,
                // Step is ready if not completed yet and all dependencies are completed            device_lock_timeout_seconds: 300,
                !completed.contains(&step.step_id)            device_lock_timeout_seconds: 300,
                    && step.depends_on.iter().all(|dep| completed.contains(dep))            device_lock_timeout_seconds: 300,
            })            device_lock_timeout_seconds: 300,
            .cloned()            device_lock_timeout_seconds: 300,
            .collect()            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
    /// Gets execution layers (topological levels) for batched execution.            device_lock_timeout_seconds: 300,
    /// Each layer contains steps that can be executed in parallel.            device_lock_timeout_seconds: 300,
    pub fn get_execution_layers(            device_lock_timeout_seconds: 300,
        &self,            device_lock_timeout_seconds: 300,
        pipeline: &[PipelineStep],            device_lock_timeout_seconds: 300,
    ) -> Result<Vec<Vec<PipelineStep>>, String> {            device_lock_timeout_seconds: 300,
        if pipeline.is_empty() {            device_lock_timeout_seconds: 300,
            return Ok(Vec::new());            device_lock_timeout_seconds: 300,
        }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        // Validate no cycles first            device_lock_timeout_seconds: 300,
        self.validate_cycle(pipeline)?;            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        let mut completed: HashSet<String> = HashSet::new();            device_lock_timeout_seconds: 300,
        let mut layers: Vec<Vec<PipelineStep>> = Vec::new();            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        loop {            device_lock_timeout_seconds: 300,
            let ready_steps = self.get_ready_steps(pipeline, &completed);            device_lock_timeout_seconds: 300,
            if ready_steps.is_empty() {            device_lock_timeout_seconds: 300,
                break;            device_lock_timeout_seconds: 300,
            }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
            // Sort by order for predictability            device_lock_timeout_seconds: 300,
            let mut ready_steps_sorted = ready_steps;            device_lock_timeout_seconds: 300,
            ready_steps_sorted.sort_by_key(|s| s.order);            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
            // Add step IDs to completed set            device_lock_timeout_seconds: 300,
            for step in &ready_steps_sorted {            device_lock_timeout_seconds: 300,
                completed.insert(step.step_id.clone());            device_lock_timeout_seconds: 300,
            }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
            layers.push(ready_steps_sorted);            device_lock_timeout_seconds: 300,
        }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        // Verify all steps are in layers            device_lock_timeout_seconds: 300,
        let total_steps = pipeline.len();            device_lock_timeout_seconds: 300,
        let steps_in_layers: usize = layers.iter().map(|l| l.len()).sum();            device_lock_timeout_seconds: 300,
        if steps_in_layers != total_steps {            device_lock_timeout_seconds: 300,
            return Err(format!(            device_lock_timeout_seconds: 300,
                "Not all steps are in execution layers: {} steps in pipeline vs {} in layers",            device_lock_timeout_seconds: 300,
                total_steps, steps_in_layers            device_lock_timeout_seconds: 300,
            ));            device_lock_timeout_seconds: 300,
        }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        Ok(layers)            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
}            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
#[cfg(test)]            device_lock_timeout_seconds: 300,
mod tests {            device_lock_timeout_seconds: 300,
    use super::*;            device_lock_timeout_seconds: 300,
    use crate::models::StepType;            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
    fn create_test_step(            device_lock_timeout_seconds: 300,
        step_id: &str,            device_lock_timeout_seconds: 300,
        order: u32,            device_lock_timeout_seconds: 300,
        step_type: StepType,            device_lock_timeout_seconds: 300,
        depends_on: Vec<&str>,            device_lock_timeout_seconds: 300,
    ) -> PipelineStep {            device_lock_timeout_seconds: 300,
        PipelineStep {            device_lock_timeout_seconds: 300,
            step_id: step_id.to_string(),            device_lock_timeout_seconds: 300,
            order,            device_lock_timeout_seconds: 300,
            step_type,            device_lock_timeout_seconds: 300,
            cmd: "echo test".to_string(),            device_lock_timeout_seconds: 300,
            env: std::collections::HashMap::new(),            device_lock_timeout_seconds: 300,
            working_dir: None,            device_lock_timeout_seconds: 300,
            must_pass: true,            device_lock_timeout_seconds: 300,
            depends_on: depends_on.into_iter().map(|s| s.to_string()).collect(),            device_lock_timeout_seconds: 300,
            always_run: false,            device_lock_timeout_seconds: 300,
            retry_policy: None, failure_policy: crate::models::FailurePolicy::Stop,            device_lock_timeout_seconds: 300,
            security_policy: Default::default(),            device_lock_timeout_seconds: 300,
            timeout_seconds: 60,            device_lock_timeout_seconds: 300,
            artifact_collection: None,            device_lock_timeout_seconds: 300,
        }            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
    #[test]            device_lock_timeout_seconds: 300,
    fn test_validate_no_cycle() {            device_lock_timeout_seconds: 300,
        let validator = DagValidator::new();            device_lock_timeout_seconds: 300,
        let pipeline = vec![            device_lock_timeout_seconds: 300,
            create_test_step("step1", 1, StepType::Shell, vec![]),            device_lock_timeout_seconds: 300,
            create_test_step("step2", 2, StepType::Shell, vec!["step1"]),            device_lock_timeout_seconds: 300,
            create_test_step("step3", 3, StepType::Shell, vec!["step1"]),            device_lock_timeout_seconds: 300,
        ];            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        assert!(validator.validate_cycle(&pipeline).is_ok());            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
    #[test]            device_lock_timeout_seconds: 300,
    fn test_validate_self_loop() {            device_lock_timeout_seconds: 300,
        let validator = DagValidator::new();            device_lock_timeout_seconds: 300,
        let pipeline = vec![create_test_step("step1", 1, StepType::Shell, vec!["step1"])];            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        let result = validator.validate_cycle(&pipeline);            device_lock_timeout_seconds: 300,
        assert!(result.is_err());            device_lock_timeout_seconds: 300,
        assert!(result.unwrap_err().contains("Cycle detected"));            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
    #[test]            device_lock_timeout_seconds: 300,
    fn test_validate_two_node_cycle() {            device_lock_timeout_seconds: 300,
        let validator = DagValidator::new();            device_lock_timeout_seconds: 300,
        let pipeline = vec![            device_lock_timeout_seconds: 300,
            create_test_step("step1", 1, StepType::Shell, vec!["step2"]),            device_lock_timeout_seconds: 300,
            create_test_step("step2", 2, StepType::Shell, vec!["step1"]),            device_lock_timeout_seconds: 300,
        ];            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        let result = validator.validate_cycle(&pipeline);            device_lock_timeout_seconds: 300,
        assert!(result.is_err());            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
    #[test]            device_lock_timeout_seconds: 300,
    fn test_get_ready_steps() {            device_lock_timeout_seconds: 300,
        let validator = DagValidator::new();            device_lock_timeout_seconds: 300,
        let pipeline = vec![            device_lock_timeout_seconds: 300,
            create_test_step("step1", 1, StepType::Shell, vec![]),            device_lock_timeout_seconds: 300,
            create_test_step("step2", 2, StepType::Shell, vec!["step1"]),            device_lock_timeout_seconds: 300,
            create_test_step("step3", 3, StepType::Shell, vec!["step1"]),            device_lock_timeout_seconds: 300,
        ];            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        let mut completed = HashSet::new();            device_lock_timeout_seconds: 300,
        let ready = validator.get_ready_steps(&pipeline, &completed);            device_lock_timeout_seconds: 300,
        assert_eq!(ready.len(), 1);            device_lock_timeout_seconds: 300,
        assert_eq!(ready[0].step_id, "step1");            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        completed.insert("step1".to_string());            device_lock_timeout_seconds: 300,
        let ready = validator.get_ready_steps(&pipeline, &completed);            device_lock_timeout_seconds: 300,
        assert_eq!(ready.len(), 2);            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
    #[test]            device_lock_timeout_seconds: 300,
    fn test_get_execution_layers() {            device_lock_timeout_seconds: 300,
        let validator = DagValidator::new();            device_lock_timeout_seconds: 300,
        let pipeline = vec![            device_lock_timeout_seconds: 300,
            create_test_step("step1", 1, StepType::Shell, vec![]),            device_lock_timeout_seconds: 300,
            create_test_step("step2", 2, StepType::Shell, vec!["step1"]),            device_lock_timeout_seconds: 300,
            create_test_step("step3", 3, StepType::Shell, vec!["step1"]),            device_lock_timeout_seconds: 300,
            create_test_step("step4", 4, StepType::Shell, vec!["step2", "step3"]),            device_lock_timeout_seconds: 300,
        ];            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        let layers = validator.get_execution_layers(&pipeline).unwrap();            device_lock_timeout_seconds: 300,
        assert_eq!(layers.len(), 3);            device_lock_timeout_seconds: 300,
        assert_eq!(layers[0].len(), 1); // step1            device_lock_timeout_seconds: 300,
        assert_eq!(layers[1].len(), 2); // step2, step3 (parallel)            device_lock_timeout_seconds: 300,
        assert_eq!(layers[2].len(), 1); // step4            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
    #[test]            device_lock_timeout_seconds: 300,
    fn test_empty_pipeline() {            device_lock_timeout_seconds: 300,
        let validator = DagValidator::new();            device_lock_timeout_seconds: 300,
        let pipeline: Vec<PipelineStep> = vec![];            device_lock_timeout_seconds: 300,
            device_lock_timeout_seconds: 300,
        assert!(validator.validate_cycle(&pipeline).is_ok());            device_lock_timeout_seconds: 300,
        assert!(validator            device_lock_timeout_seconds: 300,
            .get_execution_layers(&pipeline)            device_lock_timeout_seconds: 300,
            .unwrap()            device_lock_timeout_seconds: 300,
            .is_empty());            device_lock_timeout_seconds: 300,
    }            device_lock_timeout_seconds: 300,
}            device_lock_timeout_seconds: 300,
